Tidy setup script, fix BOD integration using misspelling in API URL

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -21,23 +21,23 @@ cat << EndOfMsg
 SpaceXLaunchBot Setup
 ---------------------
 
-This script will install these dependencies:
-- The latest version of these packages from apt:
- - python3-venv
- - redis-server
-- If pip3 is not installed, the latest version of pip for Py3 using pypa's get-pip.py
+Dependencies to be installed:
+- python3-venv from apt
+- redis-server from apt
+- pip3 from pypa (if not installed already)
 
-Make sure:
-- Python 3.6+ exists under the "python3" command
-- The SLB files exist in /opt/SpaceXLaunchBot
-- You have a Discord bot token
-- You have a Discord Bot List token
+Required:
+- Discord bot API token
+- Discord Bot List API token
+- Bots on Discord API token
 
 EndOfMsg
 
 askyn "Is this correct?" || exit
 
-cd /opt/SpaceXLaunchBot
+exists python3 || (echo "python3 does not exist, cannot continue" && exit)
+
+cd /opt/SpaceXLaunchBot || (echo "/opt/SpaceXLaunchBot does not exist, cannot continue" && exit)
 
 echo "Installing apt dependencies"
 sudo apt install python3-venv redis-server -y
@@ -46,16 +46,16 @@ sudo apt install python3-venv redis-server -y
 # - There is no confusion between system-wide pip and the pip that's copied to the venv
 # - The default packages (setuptools, wheel) are installed correctly
 if ! exists pip3; then
-    echo "Installing pip"
+    echo "Installing the latest version of pip for python3"
     curl https://bootstrap.pypa.io/get-pip.py | sudo python3
 fi
 
 echo "Setting up slb-venv"
 sudo python3 -m venv slb-venv
-echo "Installing Py3 requirements inside slb-venv"
+echo "Installing requirements inside slb-venv"
 sudo slb-venv/bin/pip3 install -r requirements.txt
 
-echo "Setting correct owner and permissions for /opt/SpaceXLaunchBot"
+echo "Setting up spacexlaunchbot user and fs permissions"
 sudo adduser --system --group --no-create-home spacexlaunchbot
 sudo chown -R spacexlaunchbot:spacexlaunchbot /opt/SpaceXLaunchBot
 # Permissions Explanation
@@ -84,12 +84,11 @@ cat << EndOfMsg
 
 Setup Finished
 --------------
-If you have a dump.rdb, stop redis, move it to /var/lib/redis and then start it again
-To start SLB enable and start it using systemctl
+To start spacexlaunchbot, enable and start it using systemctl
+To use a previous Redis dump, stop redis, move the dump to /var/lib/redis and then start redis
 
 EndOfMsg
 
 # To get a copy of dump.rdb:
-# $ sudo cp /var/lib/redis/dump.rdb ~/
-# $ sudo chwon USER dump.rdb
-# --> Download from server
+# sudo cp /var/lib/redis/dump.rdb ~/ && sudo chown USERNAME dump.rdb
+# Then download dump.rdb from ~/
